name: medx
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0
  circular_countdown_timer: ^0.2.3
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  flutter_gemini: ^2.0.4
  speech_to_text: ^6.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

